spring.application.name=ShoeStore-JAVA5-ASM
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SHOESTORE;encrypt=false;sendStringParametersAsUnicode=true;
spring.datasource.username=sa
spring.datasource.password=quocduy2006
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Encoding để không bị lỗi Font Tiếng Việt
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
# JPA & Hibernate Settings
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
# Hibernate 6 detects dialect automatically, set explicitly to avoid startup issues
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=376304087189-tivdnni2e4tuk0egp839d8fmi6sfbc64.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Multipart Config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
# Giới hạn dung lượng tối đa của toàn bộ form gửi lên (bao gồm cả chữ + ảnh)
server.tomcat.max-http-form-post-size=150MB

# --- Mail Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lehoanglong150406@gmail.com
spring.mail.password=lxgl sgja mznh uxie
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# GHN API
ghn.api.token=cb65b1f1-380f-11f1-94d3-46d409f9cf41
ghn.api.shopid=6385142

# ChatGPT AI API Key
openai.api.key=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

# PayOS Configuration (Xếp dán Key từ Dashboard vào đây)
payos.client-id=0f92b26d-2f1c-4c49-a3aa-f283f5bc1553
payos.api-key=228804d8-774c-4945-91e9-7e1080e9ed92
payos.checksum-key=e707626d5a064d8f906c835b236e01b095ee034a6a486edeeb55076093e880d8

# Gemini AI API Configuration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
gemini.api.key=

